sudo: false
language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g codecov mocha istanbul

script:
  - mocha tests/*.test.js 
  - codecov -t 16d209d9-dd12-4c1a-acca-d7a6cd80561e